export class Dados {
    nome: string = '';
    email: string = '';
    endereco: string = '';
    categoria: string = '';
    foto01: string = '';
    foto02: string = '';
    foto03: string = '';
    foto04: string = '';
    foto05: string = '';
    foto06: string = '';
    horario_inicio: string = '';
    horario_fim: string = '';
    img: string = '';
    subcategoria: string = '';
    video: string = '';
    topo: string = '';
    telefone: string = '';
    sobre: string = '';
    promocao: string = '';
    caracteristica: string = '';
    cartoes: string = '';
    capavideo: string = '';
    mapa: string = '';
    criacao: string = '';
}
